info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

spring:
  output:
    ansi:
      enabled: never

  application:
    name: ONS Notify Gateway API

  datasource:
    driverClassName: org.postgresql.Driver
    tomcat:
      initial-size: 5
      max-active: 10
      max-idle: 5
      min-idle: 3
    continue-on-error: true
    schema: classpath:/schema-cloud.sql

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    org.springframework: WARN
    uk.gov.ons.ctp: DEBUG
  profile: CLOUD

liquibase:
  user: ${cloud.services.postgresql.connection.username}
  password: ${cloud.services.postgresql.connection.password}
  default-schema: notifygatewaysvc
  url: ${cloud.services.postgresql.connection.jdbcurl}
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: true
    realm: sdc
  user:
    name: admin
    password: secret

management:
  security:
    roles: SUPERUSER
    enabled: false
  health:
    rabbit:
      enabled: false

server:
  port: 8181
  servlet-path: /

redelivery-policy:
  maxRedeliveries: 10
  initialRedeliveryDelay: 1000
  redeliveryDelay: 1000

notify:
  enabled: true
  apiKey: api-key-placeholder

rabbitmq:
  username: ${cloud.services.rabbitmq.connection.username}
  password: ${cloud.services.rabbitmq.connection.password}
  host: ${cloud.services.rabbitmq.connection.host}
  port: ${cloud.services.rabbitmq.connection.port}
  virtualhost: ${cloud.services.rabbitmq.connection.virtualhost}
  cron: "* * * * * ?"

messaging:
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  maxAttempts: 1
  prefetchCount: 10
  txSize: 1

swagger-settings:
  swagger-ui-active: false
  group-name: rm-notify-gateway-api
  title: Notify Gateway API
  description: API for ${project.artifactId}
  version: ${project.version}

comms-template-service:
  template-by-classifiers-path: /templates/
  connection-config:
    scheme: http
    host: localhost
    port: 8081