//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.02 at 07:07:04 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ons.gov.uk/ctp/response/notify/lib/action/outbound")
package uk.gov.ons.ctp.response.notify.lib.action.outbound;
