env: minikube
namespace: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  name: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

container:
  port: 80
service:
  port: 8080

resources:
  requests:
    memory: "256Mi"

notify:
  enabled: false
  apiKey: dummykey-ffffffff-ffff-ffff-ffff-ffffffffffff-ffffffff-ffff-ffff-ffff-ffffffffffff
  censusUacSmSTemplateId: ffffffff-ffff-ffff-ffff-ffffffffffff
  onsSurveysRasEmailReminderTemplateId: ffffffff-ffff-ffff-ffff-ffffffffffff
  endpoints:
    enabled: false
    infoEnabled: true

zipkin:
  enabled: false

managedRabbitMQ:
  enabled: false

dns:
  enabled: false
  wellKnownPort: 8080