REVOKE ALL PRIVILEGES ON DATABASE postgres FROM notifygatewaysvc;
DROP SCHEMA IF EXISTS notifygatewaysvc CASCADE;
DROP ROLE IF EXISTS notifygatewaysvc;

CREATE ROLE notifygatewaysvc PASSWORD 'notifygatewaysvc'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT LOGIN;

CREATE SCHEMA notifygatewaysvc AUTHORIZATION notifygatewaysvc;

REVOKE ALL ON ALL TABLES IN SCHEMA notifygatewaysvc FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA notifygatewaysvc FROM PUBLIC;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;

GRANT CONNECT ON DATABASE postgres TO notifygatewaysvc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA notifygatewaysvc TO notifygatewaysvc;
GRANT ALL ON ALL SEQUENCES IN SCHEMA notifygatewaysvc TO notifygatewaysvc;
