info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

spring:
  output:
    ansi:
      enabled: never

  application:
    name: Notify Gateway API

  sleuth:
    sampler:
      percentage: 10

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: notifygatewaysvc
    password: notifygatewaysvc
    driverClassName: org.postgresql.Driver
    tomcat:
      initial-size: 5
      max-active: 10
      max-idle: 5
      min-idle: 3

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update

  zipkin:
    enabled: true # true is the default to post to a Zipkin server at 9411

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: debug
    org.springframework.amqp: debug
    org.springframework.integration: debug
    org.springframework.cloud.sleuth.instrument.messaging.MessagingSpanExtractor: ERROR
    org.springframework.context.annotation.ConfigurationClassPostProcessor: ERROR

liquibase:
  user: notifygatewaysvc
  password: notifygatewaysvc
  default-schema: notifygatewaysvc
  url: jdbc:postgresql://localhost:6432/postgres
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: false
  user:
    name: notifygw
    password: ctp

management:
  security:
    roles: SUPERUSER
    enabled: true
  health:
    rabbit:
      enabled: false

server:
  port: 8181
  servlet-path: /

endpoints:
  autoconfig:
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  configprops:
    enabled: true
    sensitive: true
  dump:
    enabled: true
    sensitive: true
  env:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: true
  mappings:
    enabled: true
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true
  trace:
    enabled: true
    sensitive: true

redelivery-policy:
  maxRedeliveries: 10
  initialRedeliveryDelay: 1000
  redeliveryDelay: 1000

notify:
  apiKey: ctpnotifygateway-0e515090-7962-40e8-a8c7-acbacf079c21-ac979394-a989-4f79-b0e0-6abcca564393
  templateId: 966731dc-ef2e-41ad-a828-8cdd95c81ebc

rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 6672
  virtualhost: /

messaging:
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  maxAttempts: 3
  prefetchCount: 10
  txSize: 1

swagger-settings:
  swagger-ui-active: true
  group-name: rm-notify-gateway-api
  title: Notify Gateway API
  description: API for ${project.artifactId}
  version: ${project.version}
