info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

spring:
  output:
    ansi:
      enabled: never

  application:
    name: ONS Notify Gateway API

  sleuth:
    sampler:
      percentage: 1

  zipkin:
    enabled: true # true is the default to post to a Zipkin server at 9411

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    org.springframework: WARN
    uk.gov.ons.ctp: DEBUG
  profile: CLOUD

security:
  basic:
    enabled: false
  user:
    name: notifygw
    password: ctp

management:
  security:
    roles: SUPERUSER
    enabled: false
  health:
    rabbit:
      enabled: false

server:
  port: 8181
  servlet-path: /

endpoints:
  autoconfig:
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  configprops:
    enabled: true
    sensitive: true
  dump:
    enabled: true
    sensitive: true
  env:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: true
  mappings:
    enabled: true
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true
  trace:
    enabled: true
    sensitive: true

redelivery-policy:
  maxRedeliveries: 10
  initialRedeliveryDelay: 1000
  redeliveryDelay: 1000

notify:
  apiKey: ctpnotifygateway-0e515090-7962-40e8-a8c7-acbacf079c21-ac979394-a989-4f79-b0e0-6abcca564393
  templateId: 966731dc-ef2e-41ad-a828-8cdd95c81ebc

rabbitmq:
  username: ${cloud.services.rabbitmq.connection.username}
  password: ${cloud.services.rabbitmq.connection.password}
  host: ${cloud.services.rabbitmq.connection.host}
  port: ${cloud.services.rabbitmq.connection.port}
  virtualhost: ${cloud.services.rabbitmq.connection.virtualhost}
  cron: "* * * * * ?"

messaging:
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  maxAttempts: 1
  prefetchCount: 10
  txSize: 1

swagger-settings:
  swagger-ui-active: false
  group-name: rm-notify-gateway-api
  title: Notify Gateway API
  description: API for ${project.artifactId}
  version: ${project.version}
